name: Deploy Cloud Run

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker auth
      run: |
        gcloud auth configure-docker asia-northeast1-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build -t asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/terraform-simple-cloudrun:${{ github.sha }} ./app

    - name: Push Docker image
      run: |
        docker push asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/terraform-simple-cloudrun:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy terraform-simple-cloudrun \
        --image asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/terraform-simple-cloudrun:${{ github.sha }} \
        --region asia-northeast1 \
        --allow-unauthenticated

